# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/twilio/cocoapod-specs'

target 'DH5RTC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'TwilioClient', '~>1.2'
  # Pods for DH5RTC

  target 'DH5RTCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DH5RTCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
