# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DH5RTC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DH5RTC

  target 'DH5RTCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DH5RTCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
